### ISSUE TITLE
Implement login and register

### ISSUE THREAD

**Issue by Hajbo** [agnyz/elysia-realworld-example-app#30]
Implement auth related endpoints. Start with the blocking ones, the rest can be added at a later point separately.

-  Add user schema
-  Add related endpoints:
  -  Login
  -  Registration
-  Inject user to request context and implement an auth guard

**Comment by yamyam263** [comment]
I changed the description of this PR from "Issue #30" to "Closes #30", following [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
