### ISSUE TITLE
Rename `auth.ts`

### ISSUE THREAD

**Issue by yamyam263** [agnyz/elysia-realworld-example-app#52]
We should rename the `src/auth.ts` file to clarify its scope as a clear component in our architecture. 

In #47, I [offered to rename it to `auth.middleware.ts` or `auth.service.ts`](https://github.com/agnyz/elysia-realworld-example-app/pull/47#pullrequestreview-1647711979), but @Hajbo brought up the fact it currently is [out of scope of a service or middleware](https://github.com/agnyz/elysia-realworld-example-app/pull/47#issuecomment-1745422083).

We should either make it one of those, or figure out if utils are in the best practices of Nest.js.

**Comment by Hajbo** [comment]
We can probably make it into a service if we really want to

**Comment by yamyam263** [comment]
> We can probably make it into a service if we really want to

Yes! I really want to.

It would make all my dreams come true.

Please check the linked PR.
